# Generated by Django 4.1.1 on 2022-10-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_mediaservice_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaservice',
            name='file_url',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
