# Generated by Django 4.1.1 on 2022-10-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_mediaservice_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaservice',
            old_name='file_url',
            new_name='file',
        ),
    ]
