# Generated by Django 4.1.1 on 2022-10-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_file_url_mediaservice_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaservice',
            old_name='file',
            new_name='image',
        ),
    ]
