# Generated by Django 4.1.1 on 2022-10-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_file_mediaservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
