# Generated by Django 4.1.1 on 2022-10-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_mediaservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaservice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
