# Generated by Django 4.1.1 on 2022-10-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_mediaservice_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaservice',
            old_name='image',
            new_name='file_url',
        ),
    ]
